export const mockCreators = [
  {
    id: "nikita-ivanov",
    name: "Никита Иванов",
    avatar: "НИ",
    avatarColor: "#4F46E5",
    specializations: ["Мобилография", "Reels-мейкер"],
    city: "Москва",
    status: "free" as const,
    freeUntil: null,
    busyUntil: null,
    rating: 4.9,
    reviewsCount: 34,
    portfolioCount: 28,
    bio: "Снимаю контент для брендов и блогеров 4 года. Специализируюсь на fashion и beauty-контенте для Instagram и TikTok. Работал с Nike, Sephora, Lamoda.",
    isPro: true,
    portfolio: [
      { id: "p1", title: "Промо для кофейни", type: "video", aspect: "9:16", views: "142K", task: "Поднять узнаваемость кофейни Брю в Instagram", work: "Написал сценарий, снял на iPhone 15 Pro, смонтировал с саундтреком", result: "142K просмотров, +800 подписчиков за неделю", thumbnail: "#4F46E5" },
      { id: "p2", title: "Бьюти-съёмка Reels", type: "video", aspect: "9:16", views: "89K", task: "Создать вирусный контент для бьюти-бренда", work: "Снял серию из 5 роликов, продумал трендовую подачу", result: "89K просмотров, 3 ролика в топе рекомендаций", thumbnail: "#7C3AED" },
      { id: "p3", title: "Ресторанный контент", type: "video", aspect: "16:9", views: "56K", task: "Репортажная съёмка открытия ресторана", work: "Снял, смонтировал, добавил цветокоррекцию", result: "56K просмотров, публикация в Afisha.ru", thumbnail: "#059669" },
      { id: "p4", title: "Fashion-лукбук", type: "photo", aspect: "1:1", views: "34K", task: "Лукбук весенней коллекции", work: "Концепция, съёмка, ретушь 40 фото", result: "34K просмотров, коллаборация продлена", thumbnail: "#DC2626" },
      { id: "p5", title: "Промо события", type: "video", aspect: "9:16", views: "210K", task: "Анонс городского фестиваля", work: "Динамичный монтаж, музыкальная подборка", result: "210K просмотров за 48 часов", thumbnail: "#D97706" },
    ],
    reviews: [
      { author: "Алина К.", company: "Brand Manager, Coffeelab", text: "Никита — профессионал высокого уровня. Работу сдал раньше срока, всё с первого раза. Рекомендую!", rating: 5 },
      { author: "Дмитрий Р.", company: "CEO, FashionBrand", text: "Очень доволен результатом. Съёмка превзошла ожидания, видео набрало 200K+.", rating: 5 },
      { author: "Мария С.", company: "SMM-директор, Resto Group", text: "Чёткий, понимает задачу с полуслова. Уже третий проект вместе.", rating: 4 },
    ]
  },
  {
    id: "artur-makarov",
    name: "Артур Макаров",
    avatar: "АМ",
    avatarColor: "#059669",
    specializations: ["Монтажёр", "Колорист"],
    city: "Санкт-Петербург",
    status: "busy" as const,
    freeUntil: null,
    busyUntil: "25 июня",
    rating: 4.8,
    reviewsCount: 22,
    portfolioCount: 15,
    bio: "Монтирую YouTube и рекламный контент 6 лет. Работал в продакшн-студии Kion. Специализация — динамичные промо и обзоры техники.",
    isPro: true,
    portfolio: [
      { id: "p1", title: "Обзор наушников Sony", type: "video", aspect: "16:9", views: "320K", task: "Обзор наушников для YouTube-канала", work: "Монтаж, цветокоррекция, озвучка субтитров", result: "320K просмотров, лучший результат канала", thumbnail: "#0EA5E9" },
      { id: "p2", title: "Промо смартфона", type: "video", aspect: "16:9", views: "180K", task: "Рекламный ролик для бренда", work: "Монтаж с 3D-вставками, цветокоррекция", result: "180K просмотров, использован в TV", thumbnail: "#6366F1" },
    ],
    reviews: [
      { author: "Сергей П.", company: "TechReview.ru", text: "Лучший монтажёр с кем я работал. Всегда попадает в настроение и динамику.", rating: 5 },
    ]
  },
  {
    id: "elena-kozlova",
    name: "Елена Козлова",
    avatar: "ЕК",
    avatarColor: "#DC2626",
    specializations: ["Сценарист", "Продюсер"],
    city: "Москва",
    status: "free" as const,
    freeUntil: null,
    busyUntil: null,
    rating: 5.0,
    reviewsCount: 18,
    portfolioCount: 12,
    bio: "Пишу сценарии для YouTube, TikTok и рекламных роликов. 5 лет в digital. Работала с Яндексом, Сбером, ВкусВилл.",
    isPro: false,
    portfolio: [
      { id: "p1", title: "Бьюти Shorts", type: "video", aspect: "9:16", views: "540K", task: "Вирусный контент для бьюти-бренда", work: "Сценарий + продюсирование съёмки", result: "540K просмотров, +2000 продаж", thumbnail: "#EC4899" },
    ],
    reviews: []
  },
  {
    id: "ivan-petrov",
    name: "Иван Петров",
    avatar: "ИП",
    avatarColor: "#D97706",
    specializations: ["SMM", "Таргетолог"],
    city: "Удаленно",
    status: "free" as const,
    freeUntil: null,
    busyUntil: null,
    rating: 4.7,
    reviewsCount: 41,
    portfolioCount: 20,
    bio: "Веду соцсети брендов 7 лет. Настроил рекламу суммарно на 50M+ рублей. ROI моих клиентов в среднем x3.",
    isPro: true,
    portfolio: [],
    reviews: []
  },
  {
    id: "sofia-novikova",
    name: "София Новикова",
    avatar: "СН",
    avatarColor: "#7C3AED",
    specializations: ["Мобилография", "Монтажёр"],
    city: "Казань",
    status: "busy" as const,
    freeUntil: null,
    busyUntil: "1 июля",
    rating: 4.6,
    reviewsCount: 15,
    portfolioCount: 18,
    bio: "Снимаю и монтирую вертикальный контент для TikTok и Instagram. Специализация — еда и лайфстайл.",
    isPro: false,
    portfolio: [],
    reviews: []
  },
];

export const mockJobs = [
  {
    id: "job-1",
    title: "Требуется мобилограф / Reels-мейкер в бренд одежды",
    company: "ModaStyle",
    companyInitials: "MS",
    companyColor: "#4F46E5",
    location: "Москва (для съёмок) + Удалённо",
    schedule: "Съёмка 3 раза в неделю",
    experience: "Опыт от 1 года",
    budget: "120 000 ₽",
    budgetType: "fixed" as const,
    tags: ["Reels", "Fashion", "Съёмка на iPhone"],
    description: "Ищем талантливого мобилографа для создания контента наших брендов одежды. Будете снимать луки, behind-the-scenes, распаковки и трендовые Reels.",
    requirements: ["iPhone 14 Pro / 15 Pro или профессиональная камера", "Портфолио с fashion-съёмками", "Понимание актуальных трендов TikTok/Instagram"],
    postedAt: "2 дня назад",
    isHot: true,
  },
  {
    id: "job-2",
    title: "Сценарист / Креатор для YouTube-канала про технологии",
    company: "TechSpace",
    companyInitials: "TS",
    companyColor: "#059669",
    location: "Удалённо",
    schedule: "Написание 4–6 сценариев в месяц",
    experience: "Технический склад ума",
    budget: "По договорённости",
    budgetType: "negotiable" as const,
    tags: ["YouTube", "Сценарий", "Tech"],
    description: "Канал TechSpace с аудиторией 180K ищет постоянного сценариста. Пишем обзоры гаджетов, разборы технологий, тесты.",
    requirements: ["Опыт написания сценариев для YouTube", "Интерес к технологиям", "Умение доносить сложное просто"],
    postedAt: "4 дня назад",
    isHot: false,
  },
  {
    id: "job-3",
    title: "Монтажёр для ролика в кино-стиле (короткий метр)",
    company: "FilmCraft",
    companyInitials: "FC",
    companyColor: "#DC2626",
    location: "Удалённо",
    schedule: "Разовый проект, 2 недели",
    experience: "Опыт монтажа видео от 3 лет",
    budget: "80 000 ₽",
    budgetType: "fixed" as const,
    tags: ["Монтаж", "Premiere Pro", "DaVinci"],
    description: "Ищем монтажёра для короткометражного фильма (12 минут). Отснятый материал уже готов. Нужны: монтаж, цветокоррекция, звуковой дизайн.",
    requirements: ["Опыт с кино-форматом", "Портфолио нарративных работ", "DaVinci Resolve / Premiere Pro"],
    postedAt: "1 день назад",
    isHot: true,
  },
  {
    id: "job-4",
    title: "SMM-менеджер для beauty-бренда (Instagram + TikTok)",
    company: "BeautyLux",
    companyInitials: "BL",
    companyColor: "#EC4899",
    location: "Удалённо",
    schedule: "Полная занятость",
    experience: "Опыт от 2 лет в beauty-нише",
    budget: "90 000 ₽",
    budgetType: "fixed" as const,
    tags: ["SMM", "Beauty", "Instagram", "TikTok"],
    description: "Растущий beauty-бренд ищет опытного SMM-менеджера. Задачи: контент-план, публикации, взаимодействие с аудиторией, аналитика.",
    requirements: ["Кейсы ведения beauty-аккаунтов", "Понимание трендов в нише", "Навыки базового монтажа Reels"],
    postedAt: "5 дней назад",
    isHot: false,
  },
  {
    id: "job-5",
    title: "Продюсер видеосъёмок для маркетплейса",
    company: "WildberrisPro",
    companyInitials: "WP",
    companyColor: "#7C3AED",
    location: "Москва",
    schedule: "Офис 5/2 или гибрид",
    experience: "Опыт от 3 лет",
    budget: "150 000 ₽",
    budgetType: "fixed" as const,
    tags: ["Продюсер", "Съёмки", "E-commerce"],
    description: "Ищем продюсера для организации предметных и продуктовых видеосъёмок. 30–50 SKU в день.",
    requirements: ["Опыт организации поточных съёмок", "Работа с фотографами и стилистами", "Excel/Notion для трекинга"],
    postedAt: "1 неделю назад",
    isHot: false,
  },
];

export const mockPosts = [
  {
    id: "post-1",
    type: "case" as const,
    author: { name: "Никита Иванов", avatar: "НИ", color: "#4F46E5", specialization: "Мобилограф", isPro: true },
    title: "Как я сделал ролик, который набрал 500K за 3 дня",
    content: "Клиент пришёл с задачей: продвинуть небольшую кофейню. Бюджет — минимальный, ожидания — огромные. Поделюсь, что сработало.",
    videoAspect: "9:16" as const,
    videoColor: "#4F46E5",
    views: "12.4K",
    likes: 248,
    comments: 34,
    postedAt: "2 часа назад",
    tags: ["Кейс", "Мобилография", "Reels"],
  },
  {
    id: "post-2",
    type: "question" as const,
    author: { name: "Артур Макаров", avatar: "АМ", color: "#059669", specialization: "Монтажёр", isPro: true },
    title: "Какой микрофон взять для уличных съёмок до 15 000 ₽?",
    content: "Коллеги, подскажите! Часто снимаю на улице для YouTube, нужен петличный или накамерный. Бюджет — до 15 тысяч. Смотрю на Rode Wireless GO II, но может есть лучше?",
    videoAspect: null,
    videoColor: null,
    views: "3.2K",
    likes: 45,
    comments: 67,
    postedAt: "5 часов назад",
    tags: ["Вопрос", "Оборудование"],
  },
  {
    id: "post-3",
    type: "review" as const,
    author: { name: "Елена Козлова", avatar: "ЕК", color: "#DC2626", specialization: "Сценарист", isPro: false },
    title: "Ревью моего нового ролика — разберите по косточкам!",
    content: "Выкладываю новый ролик для бьюти-клиента. Хочу честный разбор: что с монтажом, нарративом, цветом. Буду рада критике — расту только так.",
    videoAspect: "9:16" as const,
    videoColor: "#EC4899",
    views: "1.8K",
    likes: 82,
    comments: 29,
    postedAt: "1 день назад",
    tags: ["Ревью", "Beauty", "Reels"],
    reviewScores: { montage: 4.2, scenario: 4.8, color: 4.1 },
  },
  {
    id: "post-4",
    type: "case" as const,
    author: { name: "Иван Петров", avatar: "ИП", color: "#D97706", specialization: "SMM", isPro: true },
    title: "ROI x4.2 для интернет-магазина: кейс таргета",
    content: "Клиент пришёл с ROAS 0.8 — то есть тратил на рекламу больше, чем зарабатывал. За 2 месяца вывел в ROAS 4.2. Рассказываю что и как.",
    videoAspect: "16:9" as const,
    videoColor: "#D97706",
    views: "8.7K",
    likes: 312,
    comments: 56,
    postedAt: "3 дня назад",
    tags: ["Кейс", "SMM", "Таргет"],
  },
];

export const mockHackathons = [
  {
    id: "hack-1",
    title: "Лучший Reels для локального бренда",
    sponsor: "CoffeeChain",
    sponsorInitials: "CC",
    sponsorColor: "#D97706",
    prize: "50 000 ₽ + контракт на 6 месяцев",
    prizeAmount: 50000,
    deadline: "18 июня 2026",
    hoursLeft: 72,
    participants: 124,
    status: "active" as const,
    category: "Мобилография",
    brief: "Снять Reels (до 60 сек) для сети кофеен CoffeeChain, раскрывающий атмосферу утреннего ритуала. Разрешено: iPhone или зеркальная камера. Материалы предоставляются.",
    stages: ["Подача работ (до 18 июня)", "Голосование комьюнити (19–21 июня)", "Решение жюри (22 июня)"],
    requirements: ["Вертикальный формат 9:16", "Длительность 30–60 секунд", "Наличие CoffeeChain-продуктов в кадре"],
  },
  {
    id: "hack-2",
    title: "Монтаж промо-видео за 48 часов",
    sponsor: "TechSpace",
    sponsorInitials: "TS",
    sponsorColor: "#4F46E5",
    prize: "30 000 ₽ + публикация на канале 200K",
    prizeAmount: 30000,
    deadline: "25 июня 2026",
    hoursLeft: 168,
    participants: 89,
    status: "active" as const,
    category: "Монтаж",
    brief: "Смонтировать 90-секундное промо из предоставленного материала (съёмки нового ноутбука). Нужны: динамичный монтаж, цветокоррекция, субтитры.",
    stages: ["Получение исходников (открыто)", "Подача работ (до 25 июня)", "Голосование (26–27 июня)"],
    requirements: ["Горизонтальный формат 16:9 + вертикальная версия", "Длительность 85–95 секунд", "Без стоковой музыки"],
  },
  {
    id: "hack-3",
    title: "Лучший сценарий вирусного видео",
    sponsor: "BeautyLux",
    sponsorInitials: "BL",
    sponsorColor: "#EC4899",
    prize: "20 000 ₽ + реализация сценария",
    prizeAmount: 20000,
    deadline: "10 июля 2026",
    hoursLeft: 696,
    participants: 203,
    status: "active" as const,
    category: "Сценарий",
    brief: "Написать сценарий для короткого вирусного видео (Reels/TikTok) для продвижения нового аромата BeautyLux. Объём: 1 страница формата сценария.",
    stages: ["Подача текстовых работ (до 10 июля)", "Шорт-лист от комьюнити (11–13 июля)", "Решение BeautyLux (14 июля)"],
    requirements: ["Формат сценария для вертикального видео", "Длительность видео 15–30 сек", "Учёт бренд-гайдов BeautyLux"],
  },
  {
    id: "hack-4",
    title: "Фешн-съёмка на смартфон",
    sponsor: "ModaStyle",
    sponsorInitials: "МС",
    sponsorColor: "#7C3AED",
    prize: "40 000 ₽ + коллаборация",
    prizeAmount: 40000,
    deadline: "5 мая 2026",
    hoursLeft: 0,
    participants: 167,
    status: "finished" as const,
    category: "Мобилография",
    brief: "Снять лук из новой коллекции ModaStyle в городской среде.",
    stages: [],
    requirements: [],
    winner: "Никита Иванов",
  },
];
