export const mockCreators = [
  {
    id: "jasur-yusupov",
    name: "Jasur Yusupov",
    avatar: "JY",
    avatarColor: "#BF5AF2",
    specializations: ["Монтажёр"],
    city: "Toshkent",
    status: "free" as const,
    freeUntil: null,
    busyUntil: null,
    rating: 4.9,
    reviewsCount: 38,
    portfolioCount: 31,
    bio: "Монтаж рекламных роликов и YouTube 5 йил. Premiere Pro, DaVinci Resolve. Динамик монтаж ва цветокоррекция бўйича ишлайман.",
    isPro: true,
    portfolio: [
      { id: "p1", title: "Реклама учун промо", type: "video", aspect: "16:9", views: "320K", task: "Бренд учун рекламавий ролик монтажи", work: "Монтаж, цветокоррекция, субтитрлар", result: "320K кўрилди, канал рекорди", thumbnail: "#BF5AF2" },
      { id: "p2", title: "YouTube обзор", type: "video", aspect: "16:9", views: "180K", task: "Техника обзори учун монтаж", work: "Динамик кесим, графика, озвучка", result: "180K кўрилди", thumbnail: "#0A84FF" },
      { id: "p3", title: "Reels монтаж", type: "video", aspect: "9:16", views: "95K", task: "Fashion бренд учун Reels", work: "Тренд монтаж, музыка подбор", result: "95K кўрилди, топ рекомендация", thumbnail: "#30D158" },
      { id: "p4", title: "Музыкавий клип", type: "video", aspect: "16:9", views: "210K", task: "Локал артист учун клип", work: "Тўлиқ постпродакшн", result: "210K кўрилди", thumbnail: "#FF9F0A" },
    ],
    reviews: [
      { author: "Aziza K.", company: "ModaUz, Brand Manager", text: "Жасур ишни вақтида ва сифатли топширди. Монтаж даражаси юқори. Тавсия қиламан!", rating: 5 },
      { author: "Bekzod R.", company: "TechUz, CEO", text: "Динамик ва аниқ монтаж. Натижа кутганимиздан зўр чиқди.", rating: 5 },
      { author: "Малика С.", company: "FilmCraft", text: "Профессионал. Ярим сўздан тушунади.", rating: 5 },
    ],
  },
  {
    id: "nilufar-rashidova",
    name: "Nilufar Rashidova",
    avatar: "NR",
    avatarColor: "#FF2D55",
    specializations: ["Мобилограф", "Reels"],
    city: "Samarqand",
    status: "busy" as const,
    freeUntil: null,
    busyUntil: "20-iyun",
    rating: 4.8,
    reviewsCount: 27,
    portfolioCount: 24,
    bio: "Мобилография ва Reels 4 йил. Fashion ва beauty контент. iPhone 15 Pro да ишлайман. Бренд ва блогерлар учун контент.",
    isPro: true,
    portfolio: [
      { id: "p1", title: "Fashion Reels", type: "video", aspect: "9:16", views: "142K", task: "Кийим бренди учун Reels", work: "Сценарий, съёмка, монтаж", result: "142K кўрилди, +800 obuna", thumbnail: "#FF2D55" },
      { id: "p2", title: "Beauty съёмка", type: "video", aspect: "9:16", views: "89K", task: "Beauty бренд учун вирал контент", work: "5 та роликдан серия", result: "89K кўрилди, 3 ролик топда", thumbnail: "#BF5AF2" },
      { id: "p3", title: "Ресторан промо", type: "video", aspect: "9:16", views: "56K", task: "Ресторан очилиши съёмкаси", work: "Съёмка ва монтаж", result: "56K кўрилди", thumbnail: "#FF9F0A" },
    ],
    reviews: [
      { author: "Dilnoza A.", company: "BeautyUz", text: "Нилуфар билан ишлаш бир завқ. Контент сифатли ва ўз вақтида.", rating: 5 },
    ],
  },
  {
    id: "azizbek-karimov",
    name: "Azizbek Karimov",
    avatar: "AK",
    avatarColor: "#0A84FF",
    specializations: ["Сценарист"],
    city: "Toshkent",
    status: "free" as const,
    freeUntil: null,
    busyUntil: null,
    rating: 5.0,
    reviewsCount: 19,
    portfolioCount: 14,
    bio: "YouTube, TikTok ва рекламавий ролик учун сценарий ёзаман. 5 йил digital да. Murakkab ғояни оддий етказаман.",
    isPro: false,
    portfolio: [
      { id: "p1", title: "Вирал Shorts", type: "video", aspect: "9:16", views: "540K", task: "Beauty бренд учун вирал контент", work: "Сценарий ва продюсирование", result: "540K кўрилди, +2000 продажа", thumbnail: "#0A84FF" },
      { id: "p2", title: "YouTube сценарий", type: "video", aspect: "16:9", views: "120K", task: "Tech канал учун обзор сценарийи", work: "Сценарий ва структура", result: "120K кўрилди", thumbnail: "#5E5CE6" },
      { id: "p3", title: "Реклама ролик", type: "video", aspect: "16:9", views: "78K", task: "Бренд учун рекламавий концепция", work: "Креатив ва сценарий", result: "78K кўрилди", thumbnail: "#30D158" },
    ],
    reviews: [
      { author: "Sardor T.", company: "TechUz", text: "Азизбек ажойиб сценарийлар ёзади. Креатив ва аниқ.", rating: 5 },
    ],
  },
  {
    id: "shahlo-mirzayeva",
    name: "Shahlo Mirzayeva",
    avatar: "SM",
    avatarColor: "#FF9F0A",
    specializations: ["SMM", "Таргетолог"],
    city: "Toshkent",
    status: "free" as const,
    freeUntil: null,
    busyUntil: null,
    rating: 4.7,
    reviewsCount: 44,
    portfolioCount: 22,
    bio: "Бренд соцсетларини 6 йил юритаман. Реклама ROI ўртача x3. Beauty ва fashion нишаси бўйича таргет.",
    isPro: true,
    portfolio: [
      { id: "p1", title: "Таргет кейс", type: "video", aspect: "16:9", views: "32K", task: "Магазин учун таргет", work: "Стратегия, креатив, оптимизация", result: "ROAS 4.2 га чиқди", thumbnail: "#FF9F0A" },
      { id: "p2", title: "SMM стратегия", type: "photo", aspect: "1:1", views: "18K", task: "Beauty бренд аккаунти", work: "Контент-план, публикациялар", result: "+5000 obuna 2 ойда", thumbnail: "#FF2D55" },
    ],
    reviews: [
      { author: "Kamola N.", company: "BeautyUz", text: "Шахло реклама бўйича профессионал. ROI сезиларли ошди.", rating: 5 },
    ],
  },
  {
    id: "doniyor-toshmatov",
    name: "Doniyor Toshmatov",
    avatar: "DT",
    avatarColor: "#5E5CE6",
    specializations: ["Продюсер"],
    city: "Buxoro",
    status: "busy" as const,
    freeUntil: null,
    busyUntil: "1-iyul",
    rating: 4.6,
    reviewsCount: 16,
    portfolioCount: 19,
    bio: "Видеосъёмка продюсери. Поточли съёмкалар ташкил этаман. Фотограф ва стилистлар билан ишлайман.",
    isPro: false,
    portfolio: [
      { id: "p1", title: "E-commerce съёмка", type: "video", aspect: "16:9", views: "45K", task: "Маркетплейс учун предметли съёмка", work: "30+ SKU ташкил ва продюсирование", result: "Конверсия +25%", thumbnail: "#5E5CE6" },
      { id: "p2", title: "Бренд видео", type: "video", aspect: "16:9", views: "67K", task: "Имидж видео продюсирование", work: "Тўлиқ продакшн ташкили", result: "67K кўрилди", thumbnail: "#BF5AF2" },
    ],
    reviews: [],
  },
  {
    id: "feruza-nazarova",
    name: "Feruza Nazarova",
    avatar: "FN",
    avatarColor: "#30D158",
    specializations: ["Мобилограф"],
    city: "Toshkent",
    status: "free" as const,
    freeUntil: null,
    busyUntil: null,
    rating: 4.9,
    reviewsCount: 33,
    portfolioCount: 27,
    bio: "Вертикал контент съёмка. TikTok ва Instagram учун. Еда ва лайфстайл нишаси бўйича мобилография.",
    isPro: true,
    portfolio: [
      { id: "p1", title: "Food Reels", type: "video", aspect: "9:16", views: "230K", task: "Ресторан учун таom съёмкаси", work: "Съёмка ва монтаж", result: "230K кўрилди, +1200 obuna", thumbnail: "#30D158" },
      { id: "p2", title: "Лайфстайл контент", type: "video", aspect: "9:16", views: "110K", task: "Бренд учун лайфстайл серия", work: "5 та ролик съёмка", result: "110K кўрилди", thumbnail: "#FF9F0A" },
      { id: "p3", title: "Кафе промо", type: "video", aspect: "9:16", views: "88K", task: "Кафе учун промо", work: "Атмосфера съёмкаси", result: "88K кўрилди", thumbnail: "#BF5AF2" },
    ],
    reviews: [
      { author: "Otabek X.", company: "FoodUz", text: "Феруза таom съёмкасида профессионал. Контент жонли чиқади.", rating: 5 },
    ],
  },
  {
    id: "otabek-xoliqov",
    name: "Otabek Xoliqov",
    avatar: "OX",
    avatarColor: "#64D2FF",
    specializations: ["Монтажёр", "Колорист"],
    city: "Toshkent",
    status: "free" as const,
    freeUntil: null,
    busyUntil: null,
    rating: 4.8,
    reviewsCount: 24,
    portfolioCount: 20,
    bio: "Монтаж ва цветокоррекция 6 йил. Кино-стиль ва реклама. DaVinci Resolve бўйича мутахассис.",
    isPro: false,
    portfolio: [
      { id: "p1", title: "Кино-стиль монтаж", type: "video", aspect: "16:9", views: "150K", task: "Короткометраж учун монтаж", work: "Монтаж, цвет, саунд-дизайн", result: "150K кўрилди, фестивал", thumbnail: "#64D2FF" },
      { id: "p2", title: "Цветокоррекция", type: "video", aspect: "16:9", views: "92K", task: "Реклама учун колоринг", work: "DaVinci колоринг", result: "92K кўрилди", thumbnail: "#0A84FF" },
    ],
    reviews: [
      { author: "Jasur Y.", company: "Монтажёр", text: "Отабек колоринг устаси. Кадр атмосферасини туяди.", rating: 5 },
    ],
  },
  {
    id: "murod-ergashev",
    name: "Murod Ergashev",
    avatar: "ME",
    avatarColor: "#FFD60A",
    specializations: ["SMM"],
    city: "Namangan",
    status: "busy" as const,
    freeUntil: null,
    busyUntil: "15-iyun",
    rating: 4.5,
    reviewsCount: 12,
    portfolioCount: 11,
    bio: "Соцсетлар бўйича SMM. Контент-план, публикациялар, аудитория билан ишлаш. Локал брендлар билан тажриба.",
    isPro: false,
    portfolio: [
      { id: "p1", title: "SMM кейс", type: "photo", aspect: "1:1", views: "14K", task: "Локал бренд аккаунти", work: "Контент-план ва ведение", result: "+3000 obuna", thumbnail: "#FFD60A" },
    ],
    reviews: [],
  },
];

export const mockJobs = [
  {
    id: "job-1",
    title: "Mобилограф Reels-мейкер fashion брендга",
    company: "ModaUz",
    companyInitials: "MU",
    companyColor: "#BF5AF2",
    location: "Toshkent (съёмка) + Remote",
    schedule: "Ҳафтада 3 марта съёмка",
    experience: "1 йилдан тажриба",
    budget: "3 500 000 сўм",
    budgetType: "fixed" as const,
    tags: ["Reels", "Fashion", "iPhone"],
    description: "Кийим брендимиз учун контент яратувчи мобилографни излаймиз. Луклар, behind-the-scenes, распаковка ва тренд Reels съёмка қиласиз.",
    requirements: ["iPhone 14 Pro / 15 Pro ёки профессионал камера", "Fashion-съёмка портфолиоси", "TikTok/Instagram трендларини билиш"],
    postedAt: "2 кун олдин",
    isHot: true,
    applicationsCount: 12,
  },
  {
    id: "job-2",
    title: "YouTube канал учун сценарист",
    company: "TechUz",
    companyInitials: "TU",
    companyColor: "#0A84FF",
    location: "Remote",
    schedule: "Ойига 4–6 сценарий",
    experience: "Технологияга қизиқиш",
    budget: "Kelishiladi",
    budgetType: "negotiable" as const,
    tags: ["YouTube", "Сценарий", "Tech"],
    description: "TechUz канали (180K аудитория) доимий сценарист излайди. Гаджет обзорлари, технология таҳлили, тестлар ёзамиз.",
    requirements: ["YouTube учун сценарий тажрибаси", "Технологияга қизиқиш", "Murakkabни оддий етказиш"],
    postedAt: "4 кун олдин",
    isHot: false,
    applicationsCount: 5,
  },
  {
    id: "job-3",
    title: "Монтажёр рекламавий ролик учун",
    company: "FilmCraft",
    companyInitials: "FC",
    companyColor: "#FF453A",
    location: "Remote",
    schedule: "Разовий лойиҳа, 2 ҳафта",
    experience: "3 йилдан монтаж тажрибаси",
    budget: "2 000 000 сўм",
    budgetType: "fixed" as const,
    tags: ["Монтаж", "Premiere Pro", "DaVinci"],
    description: "Рекламавий ролик (90 сония) учун монтажёр излаймиз. Отснятый материал тайёр. Керак: монтаж, цветокоррекция, саунд-дизайн.",
    requirements: ["Реклама форматида тажриба", "Нарратив ишлар портфолиоси", "DaVinci Resolve / Premiere Pro"],
    postedAt: "1 кун олдин",
    isHot: true,
    applicationsCount: 8,
  },
  {
    id: "job-4",
    title: "SMM beauty брендга",
    company: "BeautyUz",
    companyInitials: "BU",
    companyColor: "#FF2D55",
    location: "Remote",
    schedule: "Тўлиқ бандлик",
    experience: "Beauty нишасида 2 йил",
    budget: "2 800 000 сўм",
    budgetType: "fixed" as const,
    tags: ["SMM", "Beauty", "Instagram", "TikTok"],
    description: "Ўсаётган beauty бренд тажрибали SMM-менеджер излайди. Вазифалар: контент-план, публикациялар, аудитория, аналитика.",
    requirements: ["Beauty аккаунт юритиш кейслари", "Нишадаги трендларни тушуниш", "Reels базовий монтаж"],
    postedAt: "5 кун олдин",
    isHot: false,
    applicationsCount: 17,
  },
  {
    id: "job-5",
    title: "Продюсер видеосъёмок учун",
    company: "WBPro",
    companyInitials: "WB",
    companyColor: "#5E5CE6",
    location: "Toshkent",
    schedule: "Офис 5/2 ёки гибрид",
    experience: "3 йилдан тажриба",
    budget: "4 500 000 сўм",
    budgetType: "fixed" as const,
    tags: ["Продюсер", "Съёмка", "E-commerce"],
    description: "Предметли ва маҳсулот видеосъёмкаларини ташкил этиш учун продюсер излаймиз. Кунига 30–50 SKU.",
    requirements: ["Поточли съёмка ташкили тажрибаси", "Фотограф ва стилистлар билан ишлаш", "Excel/Notion трекинг учун"],
    postedAt: "1 ҳафта олдин",
    isHot: false,
    applicationsCount: 6,
  },
];

export const mockPosts = [
  {
    id: "post-1",
    type: "case" as const,
    author: { name: "Jasur Yusupov", avatar: "JY", color: "#BF5AF2", specialization: "Монтажёр", isPro: true },
    title: "3 кунда 500K йиққан ролик қандай монтаж қилдим",
    content: "Мижоз кичик кофейняни продвижение қилиш вазифаси билан келди. Бюджет минимал, кутиш катта. Нима ишлаганини бўлишаман.",
    videoAspect: "9:16" as const,
    videoColor: "#BF5AF2",
    views: "12.4K",
    likes: 248,
    comments: 34,
    postedAt: "2 соат олдин",
    tags: ["Кейс", "Монтаж", "Reels"],
  },
  {
    id: "post-2",
    type: "question" as const,
    author: { name: "Otabek Xoliqov", avatar: "OX", color: "#64D2FF", specialization: "Монтажёр", isPro: false },
    title: "Кўча съёмкаси учун қайси микрофон яхши, 1.5 млн гача?",
    content: "Ҳамкасблар, маслаҳат беринг! Кўпинча кўчада YouTube учун съёмка қиламан, петличка ёки накамерний керак. Бюджет 1.5 млн гача. Rode Wireless GO II га қарайман, балки яхшироғи бордир?",
    videoAspect: null,
    videoColor: null,
    views: "3.2K",
    likes: 45,
    comments: 67,
    postedAt: "5 соат олдин",
    tags: ["Савол", "Жиҳоз"],
  },
  {
    id: "post-3",
    type: "review" as const,
    author: { name: "Nilufar Rashidova", avatar: "NR", color: "#FF2D55", specialization: "Мобилограф", isPro: true },
    title: "Янги роликимни баҳоланг — суякларгача!",
    content: "Beauty мижоз учун янги ролик жойлайман. Ҳалол разбор хоҳлайман: монтаж, нарратив, цвет нима? Танқидга тайёрман — фақат шундай ўсаман.",
    videoAspect: "9:16" as const,
    videoColor: "#FF2D55",
    views: "1.8K",
    likes: 82,
    comments: 29,
    postedAt: "1 кун олдин",
    tags: ["Ревью", "Beauty", "Reels"],
    reviewScores: { montage: 4.2, scenario: 4.8, color: 4.1 },
  },
  {
    id: "post-4",
    type: "case" as const,
    author: { name: "Shahlo Mirzayeva", avatar: "SM", color: "#FF9F0A", specialization: "SMM", isPro: true },
    title: "Интернет-магазин учун ROI x4.2: таргет кейси",
    content: "Мижоз ROAS 0.8 билан келди — реклама учун ишлаганидан кўп сарфларди. 2 ойда ROAS 4.2 га чиқардим. Нима ва қандай қилганимни айтаман.",
    videoAspect: "16:9" as const,
    videoColor: "#FF9F0A",
    views: "8.7K",
    likes: 312,
    comments: 56,
    postedAt: "3 кун олдин",
    tags: ["Кейс", "SMM", "Таргет"],
  },
];

export const mockHackathons = [
  {
    id: "hack-1",
    title: "Локал бренд учун энг яхши Reels",
    sponsor: "CoffeeUz",
    sponsorInitials: "CU",
    sponsorColor: "#FF9F0A",
    prize: "1 500 000 сўм + 6 ойлик контракт",
    prizeAmount: "1 500 000 сўм",
    deadline: "18-iyun 2026",
    hoursLeft: 72,
    participants: 124,
    status: "active" as const,
    category: "Мобилография",
    brief: "CoffeeUz кофейнялар тармоғи учун эрталабки ритуал атмосферасини очувчи Reels (60 сониягача) съёмка қилинг. Рухсат: iPhone ёки зеркалка. Материаллар берилади.",
    stages: ["Ишларни топшириш (18-iyun гача)", "Комьюнити овоз бериши (19–21 iyun)", "Жюри қарори (22-iyun)"],
    requirements: ["Вертикал формат 9:16", "Давомийлик 30–60 сония", "Кадрда CoffeeUz маҳсулотлари"],
  },
  {
    id: "hack-2",
    title: "48 соатда промо-видео монтажи",
    sponsor: "TechUz",
    sponsorInitials: "TU",
    sponsorColor: "#0A84FF",
    prize: "800 000 сўм + 200K каналда публикация",
    prizeAmount: "800 000 сўм",
    deadline: "25-iyun 2026",
    hoursLeft: 168,
    participants: 89,
    status: "active" as const,
    category: "Монтаж",
    brief: "Берилган материалдан 90 сониялик промо монтаж қилинг (янги ноутбук съёмкаси). Керак: динамик монтаж, цветокоррекция, субтитрлар.",
    stages: ["Исходниклар олиш (очиқ)", "Ишларни топшириш (25-iyun гача)", "Овоз бериш (26–27 iyun)"],
    requirements: ["Горизонтал 16:9 + вертикал версия", "Давомийлик 85–95 сония", "Сток музыкасиз"],
  },
  {
    id: "hack-3",
    title: "Вирал видео учун энг яхши сценарий",
    sponsor: "BeautyUz",
    sponsorInitials: "BU",
    sponsorColor: "#FF2D55",
    prize: "500 000 сўм + сценарий реализацияси",
    prizeAmount: "500 000 сўм",
    deadline: "10-iyul 2026",
    hoursLeft: 696,
    participants: 203,
    status: "active" as const,
    category: "Сценарий",
    brief: "BeautyUz янги ифорини продвижение қилиш учун қисқа вирал видео (Reels/TikTok) сценарийини ёзинг. Ҳажм: 1 саҳифа.",
    stages: ["Матнли ишларни топшириш (10-iyul гача)", "Комьюнити шорт-лист (11–13 iyul)", "BeautyUz қарори (14-iyul)"],
    requirements: ["Вертикал видео сценарий формати", "Видео давомийлиги 15–30 сония", "BeautyUz бренд-гайд"],
  },
  {
    id: "hack-4",
    title: "Смартфонда фешн-съёмка",
    sponsor: "ModaUz",
    sponsorInitials: "MU",
    sponsorColor: "#BF5AF2",
    prize: "1 000 000 сўм + коллаборация",
    prizeAmount: "1 000 000 сўм",
    deadline: "5-may 2026",
    hoursLeft: 0,
    participants: 167,
    status: "finished" as const,
    category: "Мобилография",
    brief: "ModaUz янги коллекциясидан лукни шаҳар муҳитида съёмка қилинг.",
    stages: [],
    requirements: [],
    winner: "Nilufar Rashidova",
  },
];
